const fs = require('fs');
let c = fs.readFileSync('opportunities.html', 'utf8');

const script = `  <script>
    function requireAuth(){const u=typeof Auth!=="undefined"?Auth.get():null;if(!u){showAuthGateBanner("You must be signed in. Please log in or register first.");return false;}if(u.status==="pending"){showAuthGateBanner("Your account is pending admin approval. Please wait.");return false;}return true;}
    function showAuthGateBanner(msg){let b=document.getElementById("auth-gate-banner");if(!b){b=document.createElement("div");b.id="auth-gate-banner";b.style.cssText="position:fixed;top:80px;left:50%;transform:translateX(-50%);z-index:9000;max-width:480px;width:90%;background:linear-gradient(135deg,#0d1b3e,#1a3a6e);color:#fff;border-radius:14px;padding:20px 24px;box-shadow:0 12px 40px rgba(0,0,0,.35);display:flex;gap:14px;align-items:flex-start;";document.body.appendChild(b);}b.innerHTML='<div style="font-size:28px">\uD83D\uDD12</div><div style="flex:1"><div style="font-weight:700;font-size:15px;margin-bottom:6px;color:#f0b429">Access Restricted</div><div style="font-size:13px;opacity:.9;margin-bottom:12px">'+msg+'</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button onclick="openAuthModal(\'login\');document.getElementById(\'auth-gate-banner\').remove();" style="background:#f0b429;color:#0d1b3e;border:none;padding:8px 16px;border-radius:6px;font-weight:700;cursor:pointer;font-size:13px">Sign In</button><button onclick="openAuthModal(\'register\');document.getElementById(\'auth-gate-banner\').remove();" style="background:transparent;color:#fff;border:1px solid rgba(255,255,255,.4);padding:8px 16px;border-radius:6px;font-weight:600;cursor:pointer;font-size:13px">Register</button><button onclick="document.getElementById(\'auth-gate-banner\').remove();" style="background:transparent;color:rgba(255,255,255,.5);border:none;padding:8px;cursor:pointer;font-size:18px;margin-left:auto">\u2715</button></div></div>';clearTimeout(b._t);b._t=setTimeout(()=>b.remove(),7000);}
    [['job-app-btn','job-form'],['intern-app-btn','intern-form']].forEach(([bId,fId])=>{document.getElementById(bId).addEventListener('click',()=>{if(!requireAuth())return;const f=document.getElementById(fId);f.style.display=f.style.display==="none"||!f.style.display?"block":"none";});});
    [['show-post-job-btn','post-job-form'],['show-post-intern-btn','post-intern-form']].forEach(([bId,fId])=>{document.getElementById(bId).addEventListener('click',()=>{if(!requireAuth())return;const f=document.getElementById(fId);f.style.display=f.style.display==="none"||!f.style.display?"block":"none";});});
    document.querySelectorAll('.js-cancel-btn').forEach(btn=>{btn.addEventListener('click',()=>btn.closest('form').style.display='none');});
    document.querySelectorAll('form').forEach(form=>{form.addEventListener('submit',async e=>{e.preventDefault();if(!requireAuth())return;const ft=form.dataset.formType||(form.id==="post-job-form"?"Job Posting":form.id==="post-intern-form"?"Internship Posting":"Application");const d={};form.querySelectorAll('[name]').forEach(el=>{d[el.name]=el.value;});const btn=form.querySelector('[type="submit"]');if(btn){btn.disabled=true;btn.textContent="Submitting...";}try{await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form_type:ft,data_json:d})});}catch{}form.style.display='none';form.reset();if(btn){btn.disabled=false;btn.textContent='Submit';}if(typeof showToast==="function")showToast('Submitted!','Your '+ft+' has been received.','success');});});
  <\/script>`;

// Insert before </body>
c = c.replace('</body>', script + '\r\n</body>');
fs.writeFileSync('opportunities.html', c, 'utf8');
console.log('Done - auth gate added to opportunities.html');
